{{- if .Values.slack.webhookUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heimdall.fullname" . }}-slack
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
type: Opaque
stringData:
  SLACK_WEBHOOK_URL: {{ .Values.slack.webhookUrl | quote }}
{{- end }}
